FROM centos:7

# Set root password
RUN echo "root:password" | chpasswd

# common
#RUN yum -y update
RUN yum -y install less which net-tools sudo wget

# ssh
##  id is "user", password is "password"
## NOT WORK
#RUN useradd user --password centos1234
RUN useradd user
RUN echo "user:password" | chpasswd
RUN yum -y install openssh openssh-clients openssh-server
RUN ssh-keygen -t rsa -N "" -f /etc/ssh/ssh_host_rsa_key
RUN ssh-keygen -t dsa -N "" -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -t ecdsa -N "" -f /etc/ssh/ssh_host_ecdsa_key
RUN ssh-keygen -t ed25519 -N "" -f /etc/ssh/ssh_host_ed25519_key
RUN systemctl enable sshd

# install apache2.4
RUN yum -y install httpd

# install php5.6
RUN yum -y install epel-release
RUN rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
RUN yum remove php-*
RUN yum -y install --enablerepo=remi,remi-php56 php php-devel php-mbstring php-pdo php-gd

# enable service.
RUN systemctl enable httpd


# exec.
CMD ["/sbin/init"]