version: "3"

services:
  gradle:
    build:
      context: .
    # ホームディレクトリを全て割り当てる
    ## /home/gradle/.gradleはダウンロードしたキャッシュを含む。
    ## 別に明示的に割り当てないと認識されない。
    volumes:
      - ~/.gradle:/home/gradle/.gradle
      - ~/:/home/gradle
    working_dir: /home/gradle
    
    # コンテナが終了しないようする
    tty: true
