version: "3"

services:
  node:
    build:
      context: .
    ports:
      # for angular cli
      - "4200:4200"
      # for firebase cli
      - "9005:9005"
      # for Web app
      - "80:80"
      - "8080:8080"
      - "8888:8888"

    # ホームディレクトリを割り当ててコンテナ内で利用できるようにする
    volumes:
      - ~/:/home/node
    working_dir: /home/node
    
    # コンテナが終了しないようにする
    tty: true
